# Survey URLs, column mappings, and scoring tables

SURVEY_URLS = {
    2019: "https://github.com/StackExchange/Survey/raw/refs/heads/main/packages/archive/2019/results.csv",
    2020: "https://github.com/StackExchange/Survey/raw/refs/heads/main/packages/archive/2020/results.csv",
    2021: "https://github.com/StackExchange/Survey/raw/refs/heads/main/packages/archive/2021/results.csv",
    2022: "https://github.com/StackExchange/Survey/raw/refs/heads/main/packages/archive/2022/results.csv",
    2023: "https://github.com/StackExchange/Survey/raw/refs/heads/main/packages/archive/2023/results.csv",
    2024: "https://github.com/StackExchange/Survey/raw/refs/heads/main/packages/archive/2024/results.csv",
    2025: "https://github.com/StackExchange/Survey/raw/refs/heads/main/packages/archive/2025/results.csv",
}

# column names changed between survey years
SKILL_COLUMNS = {
    2019: [
        "LanguageWorkedWith",
        "DatabaseWorkedWith",
        "PlatformWorkedWith",
        "WebframeWorkedWith",
        "MiscTechWorkedWith",
    ],
    2020: [
        "LanguageWorkedWith",
        "DatabaseWorkedWith",
        "PlatformWorkedWith",
        "WebframeWorkedWith",
        "MiscTechWorkedWith",
    ],
    2021: [
        "LanguageHaveWorkedWith",
        "DatabaseHaveWorkedWith",
        "PlatformHaveWorkedWith",
        "WebframeHaveWorkedWith",
        "MiscTechHaveWorkedWith",
        "ToolsTechHaveWorkedWith",
    ],
    2022: [
        "LanguageHaveWorkedWith",
        "DatabaseHaveWorkedWith",
        "PlatformHaveWorkedWith",
        "WebframeHaveWorkedWith",
        "MiscTechHaveWorkedWith",
        "ToolsTechHaveWorkedWith",
    ],
    2023: [
        "LanguageHaveWorkedWith",
        "DatabaseHaveWorkedWith",
        "PlatformHaveWorkedWith",
        "WebframeHaveWorkedWith",
        "MiscTechHaveWorkedWith",
        "ToolsTechHaveWorkedWith",
    ],
    2024: [
        "LanguageHaveWorkedWith",
        "DatabaseHaveWorkedWith",
        "PlatformHaveWorkedWith",
        "WebframeHaveWorkedWith",
        "MiscTechHaveWorkedWith",
        "ToolsTechHaveWorkedWith",
    ],
    2025: [
        "LanguageHaveWorkedWith",
        "DatabaseHaveWorkedWith",
        "PlatformHaveWorkedWith",
        "WebframeHaveWorkedWith",
        "MiscTechHaveWorkedWith",
        "ToolsTechHaveWorkedWith",
    ],
}

# AI exposure scores (0-100) — higher = more likely to be automated
AI_EXPOSURE_SCORES = {
    # high risk
    "data entry clerk": 92,
    "data entry": 92,
    "telemarketer": 90,
    "travel agent": 87,
    "insurance underwriter": 85,
    "tax preparer": 84,
    "loan officer": 82,
    "receptionist": 80,
    "bookkeeper": 78,
    "customer service representative": 76,
    "content writer": 75,
    "proofreader": 74,
    "translator": 73,
    "market research analyst": 70,
    # medium risk
    "data analyst": 60,
    "business analyst": 58,
    "financial analyst": 55,
    "hr specialist": 52,
    "paralegal": 50,
    "graphic designer": 48,
    "digital marketer": 45,
    "project manager": 42,
    "product manager": 40,
    # low risk
    "software engineer": 35,
    "full stack developer": 33,
    "backend developer": 32,
    "frontend developer": 34,
    "devops engineer": 28,
    "data scientist": 30,
    "data engineer": 30,
    "ml engineer": 20,
    "machine learning engineer": 20,
    "ai engineer": 15,
    "ai researcher": 12,
    "cybersecurity analyst": 18,
    "ai security engineer": 12,
    "cloud architect": 25,
    "blockchain developer": 22,
    "ux designer": 35,
    "robotics engineer": 15,
    "mlops engineer": 14,
    "prompt engineer": 25,
}

# AI resistance scores (0-1), used in survival score calc.
# skills not listed here default to 0.5
AI_RESISTANT_SKILLS = {
    "Python": 0.85,
    "Machine Learning": 0.90,
    "AI": 0.92,
    "Cybersecurity": 0.88,
    "Cloud": 0.82,
    "Docker": 0.80,
    "Kubernetes": 0.82,
    "MLOps": 0.90,
    "LangChain": 0.93,
    "TensorFlow": 0.88,
    "PyTorch": 0.89,
    "Rust": 0.85,
    "Go": 0.80,
    "Terraform": 0.78,
    "PostgreSQL": 0.72,
    "SQL": 0.68,
    "JavaScript": 0.65,
    "TypeScript": 0.70,
    "React.js": 0.65,
    "Node.js": 0.63,
    "AWS": 0.78,
    "Azure": 0.76,
    "Google Cloud": 0.75,
    "Apache Spark": 0.74,
    "Scala": 0.72,
    "Java": 0.60,
    "C#": 0.60,
    "C++": 0.65,
    "Bash/Shell": 0.62,
    "Linux": 0.70,
    "PHP": 0.45,
    "Visual Basic": 0.25,
    "COBOL": 0.20,
    "Perl": 0.30,
    "VBA": 0.25,
    "Assembly": 0.40,
    "Delphi": 0.22,
    "MATLAB": 0.50,
    "R": 0.60,
    "Julia": 0.72,
    "Kotlin": 0.68,
    "Swift": 0.66,
    "Dart": 0.64,
    "MongoDB": 0.65,
    "Redis": 0.68,
    "Elasticsearch": 0.70,
    "Cassandra": 0.66,
    "Kafka": 0.75,
    "dbt": 0.72,
    "Ansible": 0.74,
    "Jenkins": 0.66,
    "Git": 0.75,
    "GitHub Actions": 0.74,
}
